export enum TableActionType {
    ADD_TABLE = 'ADD_TABLE',
    REMOVE_TABLE = 'REMOVE_TABLE',
    GET_TABLES = 'GET_TABLES',
    CHANGE_NAME = 'CHANGE_NAME'
}

export enum TaskActionType {
    ADD_TASK = 'ADD_TASK',
    REMOVE_TASK = 'REMOVE_TASK',
    GET_TASKS = 'GET_TASKS',
    REMOVE_TASKS_WITH_TABLE = 'REMOVE_TASKS_WITH_TABLE',
    COMPLETED_TASK = 'COMPLETED_TASK',
    UNCOMPLETE_TASK = 'UNCOMPLETE_TASK'
}
